name: Lint

on: 
  push:
    paths: 
      - '**/*.py'

jobs:
  ruff:
    name: Code Linter
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10
    
    - name: Install ruff Linter
      run: pip install ruff
      
    - name: Run ruff Linter
      run: ruff check --output-format=github app/